global using Plugin.Maui.Audio;
global using MauiChat.Platforms.Views;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Threading.Tasks;
